#!/usr/bin/env python3
"""Regenerates public/logo.svg — the FLASH-bolt-CARDS wordmark.

Run it only to change the mark; the SVG it writes is the artefact the app and
anything else uses, and it is checked in.

    pip install fonttools brotli      # brotli is what reads a .woff2
    pnpm run build                    # puts IBM Plex Mono where this can find it
    python3 tools/wordmark.py

Two things are worth knowing before editing.

The letters are outlines, not <text>. An SVG that reaches a machine without IBM
Plex Mono would otherwise fall back to some other mono, and the frame — whose
width is baked in — would no longer fit the words inside it.

The spacing is measured on ink, not on advance widths. A browser's getBBox on
an SVG <text> returns the advance box, which in a monospace face is a good deal
wider than the letters: spacing the bolt that way leaves it visibly closer to
one word than the other. Every position here comes from a BoundsPen.
"""
from pathlib import Path
import sys

from fontTools.misc.transform import Transform
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

OUT = Path("public/logo.svg")

# 19px with 0.14em of tracking is what the .label class sets, so the mark and
# the interface are lettered in the same voice.
SIZE, TRACK = 19.0, 3.4
GAP, PAD = 15.0, 34.0            # ink either side of the bolt; ink to the frame
HEIGHT = 76.0
FRAME_STROKE, RADIUS = 5.0, 16.0
BOLT_STROKE = 2.0
BOLT = "M18 0 L0 42 H12 L9 72 L30 26 H16 Z"      # ink 30 wide, 72 tall
BOLT_W, BOLT_H = 30.0, 72.0

CREAM, RED, GOLD, INK = "#E0D4BF", "#B72622", "#DAAD3B", "#2C2C2A"


def find_font(family="IBM Plex Mono Regular", needed="FLASHCARDS"):
    """The font next/font downloaded during the last build.

    next/font splits a face into per-unicode-range subsets that all carry the
    same name, so the name alone will happily hand back a file with no Latin
    letters in it. The glyphs have to be there too.
    """
    for path in sorted(Path(".next/static/media").glob("*.woff2")):
        try:
            font = TTFont(path)
        except Exception:
            continue
        if font["name"].getDebugName(4) != family:
            continue
        cmap = font.getBestCmap()
        if all(ord(ch) in cmap for ch in needed):
            return font
    sys.exit(
        f"Could not find {family} under .next/static/media.\n"
        "Run `pnpm run build` first — next/font fetches it at build time."
    )


def main():
    font = find_font()
    cmap, glyphs = font.getBestCmap(), font.getGlyphSet()
    scale = SIZE / font["head"].unitsPerEm

    def word(text, baseline):
        """A draw() that renders `text` from a given x, plus its ink bounds."""
        def draw(pen, origin):
            x = origin
            for ch in text:
                glyph = glyphs[cmap[ord(ch)]]
                glyph.draw(TransformPen(pen, Transform(scale, 0, 0, -scale, x, baseline)))
                x += glyph.width * scale + TRACK

        bounds = BoundsPen(glyphs)
        draw(bounds, 0.0)
        return draw, bounds.bounds

    # Centre the letters by their ink rather than trusting the baseline, so the
    # words sit in the middle of the frame however the face is drawn.
    _, probe = word("FLASHCARDS", 45.0)
    baseline = 45.0 + (HEIGHT / 2 - (probe[1] + probe[3]) / 2)

    draw_flash, (fx0, _, fx1, _) = word("FLASH", baseline)
    draw_cards, (cx0, _, cx1, _) = word("CARDS", baseline)

    # Left to right, on ink. The bolt's stroke straddles its path, so half of it
    # counts as ink on each side.
    flash_right = PAD + (fx1 - fx0)
    bolt_x = flash_right + GAP + BOLT_STROKE / 2
    bolt_right = bolt_x + BOLT_W + BOLT_STROKE / 2
    cards_right = bolt_right + GAP + (cx1 - cx0)
    width = round(cards_right + PAD, 2)

    flash = SVGPathPen(glyphs, ntos=lambda v: f"{v:.2f}")
    draw_flash(flash, PAD - fx0)
    cards = SVGPathPen(glyphs, ntos=lambda v: f"{v:.2f}")
    draw_cards(cards, bolt_right + GAP - cx0)

    OUT.write_text(f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width:g} {HEIGHT:g}" width="{width:g}" height="{HEIGHT:g}" role="img" aria-label="Flashcards">
  <title>Flashcards</title>
  <!--
    The wordmark, on a transparent ground. Generated by tools/wordmark.py —
    edit that, not this. The letters are outlines so the mark cannot fall back
    to another mono and pull the spacing out from under the frame, and the
    spacing is measured on ink: {GAP:g} either side of the bolt, {PAD:g} to the frame.
  -->
  <rect x="0" y="0" width="{width:g}" height="{HEIGHT:g}" rx="{RADIUS:g}" fill="{CREAM}"/>
  <rect x="{FRAME_STROKE / 2:g}" y="{FRAME_STROKE / 2:g}" width="{width - FRAME_STROKE:g}" height="{HEIGHT - FRAME_STROKE:g}" rx="{RADIUS - FRAME_STROKE / 2:g}" fill="none" stroke="{RED}" stroke-width="{FRAME_STROKE:g}"/>
  <path d="{flash.getCommands()}" fill="{INK}"/>
  <g transform="translate({bolt_x:.2f},{(HEIGHT - BOLT_H) / 2:g})">
    <path d="{BOLT}" fill="{GOLD}" stroke="{RED}" stroke-width="{BOLT_STROKE:g}" stroke-linejoin="round"/>
  </g>
  <path d="{cards.getCommands()}" fill="{INK}"/>
</svg>
''')
    print(f"{OUT}: {width:g}x{HEIGHT:g}, gaps {GAP:g}/{GAP:g} on ink")


if __name__ == "__main__":
    main()
